### PR TITLE
Use Go's standard libs

### LINKED ISSUE #2: Plugin crashes on Android/Termux
When the plugin is activated via Ctrl+E tree the plugin crashes when trying to list files in current directory:

```
<string>138: attempt to index a non-table object(nil)
stack traceback:
    <string>:138: in function 'scanDir'
    <string>:45: in function 'refreshTree'
    <string>:24: in function 'OpenTree'
    <string>:37: in main chunk
    [G]: ?
```

After pressing a key the left panel is empty.
Current directory as shown by **pwd** in Termux's commandline: **/data/data/com.termux/files/home**
The plugin is installed into: **/data/data/com.termux/files/home/.config/micro/plugins/filemanager**

### PR DESCRIPTION
**Pull request by sum01**
Fixes Windows support, and makes the plugin more portable since it isn't using `io.popen` now.

Tesed on both Linux & Windows.

This could possibly fix #2 but I haven't personally tested on Android.

### CODE REVIEW

**Comment by tommyshem** [comment]
I was working on the debugging branch looking at this but did not have much time, this looks like the same work but if yours works then we will merge. I will test when I get time.

**Comment by tommyshem** [comment]
Tested on Linux Arch and I get this error
```bash
runtime error: invalid memory address or nil pointer dereference
stack traceback:
	filemanager:182: in function 'scanDir'
	filemanager:63: in function 'refreshTree'
	filemanager:27: in function 'OpenTree'
	filemanager:16: in main chunk
	[G]: ?
```
Using micro editor version 
Version: 1.3.4-dev.92
Commit hash: e4c2f5d
Compiled on November 20, 2017

**Comment by sum01** [comment]
Weird. I have no issues on Micro v1.3.3, and I tested on Arch Linux & Windows 10.

Did v1.3.4 change how Go libs are imported?

**Comment by sum01** [comment]
I changed the last Lua command `os.execute` to use Go's libs instead. Sorry about pushing twice, forgot to use the full path the first time.

I don't think I'm missing anything now?

**Comment by tommyshem** [comment]
Yes you are right I have looked at the history and on 1st oct commit 46ced98 the lua call was changed from ioutil to io/ioutil which is causing the problem between versions. If this is stopping in before the next release of micro editor then we will have to target the next version as min requirement.

**Comment by sum01** [comment]
Oh, just saw https://github.com/zyedidia/micro/commit/2ee7adb19672a4c77032caaeb2611e13abfe538d so I guess it'd be backwards-compatible to do it the current way I do it, instead of changing to `import("io/ioutil")`, at least once that commit hits nightly.

**Comment by tommyshem** [comment]
I will test when I get back from work. And if it works then I will merge it.

File: filemanager.lua [hunk 1]
```diff
@@ -175,40 +174,55 @@ function preQuitAll(view) treeView.Buf.IsModified = false end
...
+
+  -- Returns a FileInfo on the current file/path
+  local file_info = go_os.Stat(check_path)
+
+  if file_info ~= nil then
+    -- Returns the true/false of if the file is a directory
+    return file_info:IsDir()
+  else
+    messenger:AddLog("isDir() failed, returning nil")
+    return nil
```
Comment (tommyshem) [inline filemanager.lua]: Not sure we should have a nil return without checking in the code where it is used. As this could cause problems if it fails. (nil checking)

**Comment by tommyshem** [comment]
I have tested on Linux and windows everything looks like it is working ok.
Just need feed back on the nil checking above.

File: filemanager.lua (hunk 1 above)
Comment (sum01) [reply filemanager.lua]: Everywhere in the code that `isDir` is used is only in `if`'s, so it will simply fail the `if isDir(file)` or whatever. 

Nothing should "explode", as it's basically like saying `false` but with some more verbosity if it ever needs to be checked against more thoroughly.

Comment (sum01) [reply filemanager.lua]: Of course if you're still worried, all `if isDir(file)` lines could be changed to `if isDir(file) and not isDir(file) == nil`, but that seems a bit excessive.

Comment (tommyshem) [reply filemanager.lua]: @NicolaiSoeborg This is ready to be merged if you are happy with it.
Could not find any fails when testing and it works on Android/Termux so #2 can be closed when merged.

Comment (NicolaiSoeborg) [reply filemanager.lua]: I'm very happy! Will merge now.
